### ISSUE TITLE
Able to participate to award even after end date

### ISSUE THREAD

**Issue by antonionardella** [soonlabs/soonaverse-dao#119]
**Describe the bug**
This award is set with end on the 3rd of Dec 2021. Today is the 5th Dec 2021. I was able to click participate, submit and sign my message.

**To Reproduce**
1. Go to a space with an expired award
2. Click on participate, submit message and sign
No error

**Expected behavior**
I imagine that the system should show the award as expired and not enable the submission of a message.

**Screenshots**
![image](https://user-images.githubusercontent.com/7383572/144760768-f45955d2-9054-410d-9294-ec3a7a34001b.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Chromium

**Additional context**

Thanks! (Can I still have the award 😉)

**Comment by adamkundrat** [comment]
I just checked we allow participate but guardian will not be able to give you badge because it's past end date. But yeah that's not good enough.

We'll do two improvements on awards:
- fix above. Space should show as complete.
- introduce draft status on Award same way it works on proposal.

It'll come in next one to two days.

**Comment by adamkundrat** [comment]
We've introduce Pending status for awards and also have clean up statuses. Have a look and let me know if it's better.

We're about start 2 weekly sprint and more improvements will come on 17/12.
