### ISSUE TITLE
Create CSV Button not working

### ISSUE THREAD

**Issue by ebk1960** [soonlabs/soonaverse-dao#306]
In the Create NFT area:

I can create a single NFT and can make it available for sale - see 'Jack Russell Collection' - single image. 

When I select the 'Multiple'  button to create a multi image collection, while I can upload four .jpg’s, without issue, its when I try to generate a CSV list for these uploaded images by hitting the 'Generate CSV' button, there is a problem.... as nothing happens. 

Note: I uploaded the .jpg images directly from my hard drive. I'm uncertain what, if any, additional actions I should have taken before image upload. Additionally, there was no error dialogue box that appeared when I hit the 'Generate CSV' button.

**Comment by adamkundrat** [comment]
I suspect this might because we allow any filename and it breaks our logic. it breaks in CSV too, i had this happening to me.

@Gundavri Please test and restrict filenames only to alphanumeric values (no spaces, special characters, etc. ) and extensions as defined in nz-upload. Please re-test properly.

@ebk1960 could you provide list of filenames you were trying to upload pls?

**Comment by ebk1960** [comment]
Surely,
20170819_163901(1).jpg
20170903_223146.jpg
20170903_223712.jpg
20180102_225357.jpg
