### ISSUE TITLE
Collection incorrectly rejected 

### ISSUE THREAD

**Issue by fionn1989** [soonlabs/soonaverse-dao#646]
Issue #643 was reporting an IF Copyright infraction due to the use of the IOTA logo in the following collection:
https://soonaverse.com/collection/0x0ecc0c3139d957eb9b7472cce9d899b839a23108

IOTA Logo related information from Iota page:
_The IOTA logo symbolizes the IOTA Tangle and its associated suite of open-source distributed ledger and machine-to-machine technologies. This logo is permissively and non-exclusively [license](https://creativecommons.org/licenses/by-sa/4.0/legalcode)d under the Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license. The full legal text of the license should be consulted here._

If we check the licence, clicking on the link....

_Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
This is a human-readable summary of (and not a substitute for) the license. [Disclaimer](https://creativecommons.org/licenses/by-sa/4.0/?#).
You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
for any purpose, even commercially._

The IOTA logo can be remixed, transformed and used to built new creations even with comercial purposes. In addition, there is a bunch of collections which are using the IOTA logo in Soonaverse.

There is no copyright infraction....in fact, this point was analysed when we started working in our creations...so we kindly ask to enable the collection again.

**Comment by adamunchained** [comment]
@Phyloiota can you comment?

**Comment by Phyloiota** [comment]
![image](https://user-images.githubusercontent.com/77154511/163722319-a6ae347a-4be5-4398-bcc8-43b2551784f5.png)


From our Website:
The IOTA project has two main logos: the IOTA logo and the IOTA Foundation logo. Both sets of logos are trademarked. However, they are subject to different licensing schemes and separate usage policies:

Persons or entities wishing to use either logo should carefully read and comply with the information below.
IOTA Logo

The IOTA logo symbolizes the IOTA Tangle and its associated suite of open-source distributed ledger and machine-to-machine technologies. This logo is permissively and non-exclusively licensed under the Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license. The full legal text of the license should be consulted [here.](https://creativecommons.org/licenses/by-sa/4.0/?)

Parties interested in using the IOTA logo should:

    consult and adhere to the full terms and conditions listed on the CC BY-SA 4.0 website, as updated from time to time; and
    follow the IOTA logo style guide instructions, as updated here from time to time; and
    make it clear that the Party using the logo has no affiliation with the IOTA Foundation and that the use of the logo does not constitute an endorsement by the IOTA Foundation.

As an overview, three main categories of IOTA logo usage are permitted under this Creative Commons license
1. Non-commercial / not-for-profit uses:

Developers, community projects, partner organizations, etc. may make use of the IOTA logo provided they do so on a non-commercial / not-for-profit basis. Some examples of permitted usages might include:

    Printing IOTA t-shirts, hats, or other “swag” items to be given away for free or sold to friends and family members on a cost-recovery only basis.
    Creating an IOTA fan page on a social media outlet for purposes of educating IOTA users or potential users, stimulating developer or researcher discussions, and/or generally raising awareness about IOTA.
    Designing and distributing marketing materials to advertise IOTA meet-ups, hackathons, conferences, developer workshops or other similar events organized on a not-for-profit basis.

The above examples are only meant to be illustrative and not exhaustive.
2. “IOTA identifier” uses by journalists, analysts, exchanges, & others:

Projects and publications may use the IOTA logo to identify IOTA and distinguish it from other technologies in situations where multiple different technologies (for example, IOTA, BTC, ETH, etc) are presented together and there is a need to distinguish one from the other. Examples might include:

    press articles, social media posts, or technical reports that discuss multiple projects;
    cryptocurrency exchanges and other entities whose activities involve commercial or non-commercial offerings of both IOTA-related and non-IOTA-related products and services.

3. “Powered by IOTA” uses:

Projects that draw from, interface with, or otherwise make use of the IOTA Tangle and/or another IOTA technology may use the IOTA logo to indicate that their app / dapp / PoC / project / etc. is “powered by IOTA”. Note that displaying a “powered by IOTA” logo allows you to make use of the IOTA logo in both commercial (for-profit) and non-commercial (non-profit) projects while also complying with the CC BY-SA 4.0 license requirement that your use of the logo does not in any way suggest that the licensor endorses you or your project.

These examples are also intended to be illustrative rather than exhaustive. Once again, all “identifier” uses of the IOTA logo must always comply with the CC BY-SA 4.0 license requirement that your use of the logo does not in any way suggest that the licensor endorses you or your project.
IOTA Foundation logo

The IOTA Foundation logo is associated with the Berlin-incorporated, non-profit foundation that stewards the development and standardization of core IOTA technologies. This logo is trademarked and its use is restricted to the IOTA Foundation and official partners to whom the IOTA Foundation grants its explicit written consent on a per-use basis. No other uses of the IOTA Foundation logo are permitted.

**Comment by fionn1989** [comment]
Thanks Phyloiota,

First of all, IOTA Foundation logos have not been used, so lets exclude them from the discusion.

The IOTA logo that has been included in our creations is under Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license, so lets focus on this licence: **(All our commens typed in bold)**


### Taking the sumary of this Creative Commons licence, lets see:

Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
You are free to:
Share — copy and redistribute the material in any medium or format
**Not applicable. No direct copy of official IOTA logo has been performed, so the examples provided in the IOTA web page that you mention are not dealing with the case of logo modification which corresponds to our case**


Adapt — remix, transform, and build upon the material
for any purpose, even commercially.
**This is the case of the use of the logo in our creations and many others that are using the IOTA logo**

This license is acceptable for Free Cultural Works.
The licensor cannot revoke these freedoms as long as you follow the license terms.



### Regarding the terms:
Attribution — You must give [appropriate credit](https://creativecommons.org/licenses/by-sa/4.0/?#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by-sa/4.0/?#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
**Our main Soonaverse Space is a tribute to IOTA ecosystem. It has been created with the goal of building a DAO where members can share trading opinions, learn about chart analysis and share their support to IOTA. Based on this approach, the whole Space, and all NFT creations are related to IOTA. The Credit to the original IOTA Foundation is inherent to the Space and the collections themselves, since they are a tribute to them. The collection description is clearly indicating the reference: "sober and customized items in white ΙΟΤΛ logo." In addition, the description of our Space, mentions it**


ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the [same license](https://creativecommons.org/licenses/by-sa/4.0/?#) as the original.
**In this case, we have created our creations by modifying the original IOTA logo. This creations have been minted as NFTs so that some members can be the owners of the very first and unique item. Anybody can download our NFT creation and use it as a reference for new creations. If it is needed to add a explicit note in our space description, please let us know and we will add it in the collection desciption to be fully compliant. We did not do it, because we have not seen that reference in any other NFT collection using the IOTA logo (There are many of them)** 

No additional restrictions — You may not apply legal terms or [technological measures](https://creativecommons.org/licenses/by-sa/4.0/?#) that legally restrict others from doing anything the license permits.



**With all this analysis of the licence (that we performed when we decided to launch this project), we still do not see what point indicated in the licence is being violated. It is very important for us that you please confirm exactly in an unambiguous way which point (or in what form) has been violated, or what extra information we have to include in the description in order to be fully compliant in future collections.**

**If you consider the licence has been violated, I guess that many other big and famous collections included in Soonaverse (Some of them with royalties being received by Soonlabs) are using the IOTA Logo and have the same problem. As examples: iotapes, creamies, iotawhales, IOTA HISTORY, tanglebees, iotaholics, castersofgaia, misteriousmorons...**

**At the end, many of these collections (as ours) are IOTA related and all of them are contributing to the IOTA Ecosystem in form of free marketing for the IF and helping the grow of the environment that is being built. In fact this is why we understand the IOTA logo is licensed this way (CC BY-SA 4.0), to be easily reused**

**To finish our arguments, it must be said that this discussion could have had more sense in the moment of the first approval of the collection, before anybody could access to it. Rejecting a collection that has already been validated and active for more than 2 weeks makes a huge damage to Soonlabs and Iota reliability. (People have traded for an NFT and now it is going to dissapear...)**


**We look forward for your response and hoping you reconsider the collection re-activation or any extra requirement that may be included in the description in order to upload it again**

**Comment by Phyloiota** [comment]
Hello

After our legal team has reviewed the "Tribute to IOTA" collection, we are okay with opening it again under the following conditions:
**Please add these things to the collection:**
A disclaimer that this project is not endorsed by the IOTA Foundation (that you currently only have in the description of your space), and please also add:
“IOTA and the IOTA logo are trademarks of the IOTA Foundation (https://www.iota.org/).”

We do this as our new Logo usage and trademark policy is anyway gonna be issued in the coming days and will be handling those things in a much more straightforward way.

@adamunchained FYI

**Comment by adamunchained** [comment]
@fionn1989 - please confirm once above added and we'll enable collection again.

**Comment by adamunchained** [comment]
collection approved again

**Comment by fionn1989** [comment]
Collection information has been updated with required disclamer.

@adamunchained Could you also enable collection indicated in #644 in order to do the same and update the issue?
https://soonaverse.com/collection/0x0b88a9c1d1515f9f2cfc3798d7216ad2eef3201e

**Comment by adamunchained** [comment]
Closing as this has been corrected.
